import {
  LayoutDashboard,
  Users,
  UserPlus,
  UserCog,
  ArrowRightLeft,
  ArrowUpDown,
  User,
  ClipboardList,
  School,
  BookOpen,
  GraduationCap,
  Receipt,
  MessageSquare,
  Wallet,
  BadgeDollarSign,
  Database,
  CheckSquare,
  Building2,
  Bus,
  FileBarChart,
  Award,
  FileQuestion,
  Users2,
  UsersRound,
} from "lucide-react";
export const navItems = [
  {
    label: "Dashboard",
    icon: LayoutDashboard,
    subItems: [
      { label: "School Dashboard", href: "/dashboard/school" },
      { label: "Teacher Dashboard", href: "/dashboard/teacher" },
      { label: "Student Dashboard", href: "/dashboard/student" },
      { label: "Fee Dashboard", href: "/dashboard/fee" },
      { label: "Accounts Dashboard", href: "/dashboard/accounts" },
    ],
  },
  {
    label: "Student",
    icon: Users,
    subItems: [
      { label: "All Students", href: "/students/all", icon: Users2 },
      { label: "Add Student", href: "/students/add", icon: UserPlus },
      { label: "Assign Class", href: "/students/assign-class", icon: UserCog },
      { label: "Transfer", href: "/students/transfer", icon: ArrowRightLeft },
      { label: "Promote", href: "/students/promote", icon: ArrowUpDown },
    ],
  },
  {
    label: "parents",
    icon: UsersRound,
    href: "/parent",
  },
  {
    label: "User Management",
    icon: User,
    subItems: [
      { label: "All Users", href: "/users" },
      { label: "User Subjects", href: "/users/subjects" },
      { label: "User Classes", href: "/users/classes" },
    ],
  },
  {
    label: "Staff Attendance",
    icon: ClipboardList,
    subItems: [
      { label: "Attendance", href: "/staff/attendance" },
      { label: "Leave Request", href: "/staff/leave/request" },
      { label: "Leave Records", href: "/staff/leave/records" },
    ],
  },
  {
    label: "School Management",
    icon: School,
    subItems: [
      { label: "Classes", href: "/school/classes" },
      { label: "Subjects", href: "/school/subjects" },
      { label: "Timetable", href: "/school/timetable" },
      { label: "Circulars", href: "/school/circulars" },
      { label: "Holidays", href: "/school/holidays" },
      { label: "CCA", href: "/school/cca" },
    ],
  },
  {
    label: "Class Work",
    icon: BookOpen,
    subItems: [
      { label: "Attendance", href: "/classwork/attendance" },
      { label: "Leave Requests", href: "/classwork/leave" },
      { label: "Homework", href: "/classwork/homework" },
      { label: "Assignments", href: "/classwork/assignments" },
      { label: "Notices", href: "/classwork/notices" },
      { label: "Activities", href: "/classwork/activities" },
      { label: "Timetable", href: "/classwork/timetable" },
      { label: "Subjects", href: "/classwork/subjects" },
      { label: "Chapters", href: "/classwork/chapters" },
      { label: "Notes", href: "/classwork/notes" },
    ],
  },
  {
    label: "Exam & Results",
    icon: GraduationCap,
    subItems: [
      { label: "Create Exam", href: "/exams/create" },
      { label: "Add Marks", href: "/exams/marks" },
      { label: "Generate Marksheet", href: "/exams/marksheet" },
    ],
  },
  {
    label: "Fee Management",
    icon: Receipt,
    subItems: [
      { label: "Generate Invoice", href: "/fees/invoice" },
      { label: "Custom Fee", href: "/fees/custom" },
      { label: "Make Payment", href: "/fees/payment" },
      { label: "Fee Receipt", href: "/fees/receipt" },
      { label: "Class Fee Structure", href: "/fees/class-structure" },
      { label: "Student Fee Structure", href: "/fees/student-structure" },
    ],
  },
  {
    label: "Complaints",
    icon: MessageSquare,
    href: "/complaints",
  },
  {
    label: "Accounts",
    icon: Wallet,
    subItems: [
      { label: "Company", href: "/accounts/company" },
      { label: "Donation", href: "/accounts/donation" },
      { label: "Loan", href: "/accounts/loan" },
      { label: "Scholarship", href: "/accounts/scholarship" },
      { label: "User Accounts", href: "/accounts/users" },
      { label: "School Accounts", href: "/accounts/school" },
      { label: "Work Order", href: "/accounts/work-order" },
      { label: "Payment", href: "/accounts/payment" },
      { label: "Transaction", href: "/accounts/transaction" },
      { label: "Balance Sheet", href: "/accounts/balance" },
      { label: "Profit & Loss", href: "/accounts/profit-loss" },
    ],
  },
  {
    label: "Pay Role",
    icon: BadgeDollarSign,
    href: "/payroll",
  },
  {
    label: "Master Data",
    icon: Database,
    subItems: [
      { label: "User", href: "/master/users" },
      { label: "User Session", href: "/master/User-Session" },
      { label: "Classes", href: "/master/classes" },
      { label: "Class Session", href: "/master/class-session" },
      { label: "Bus", href: "/master/bus" },
      { label: "Bus Session", href: "/master/bus-session" },
      { label: "Fee Heads", href: "/master/fee-heads" },
      { label: "period", href: "/master/period" },
      { label: "Sessions", href: "/master/sessions" },
      { label: "Current Sessions", href: "/master/current-session" },
      { label: "Student Fees", href: "/master/student-fees" },
      { label: "Class Fees", href: "/master/class-fees" },
      { label: "Subjects", href: "/master/subjects" },
      { label: "User Permissions", href: "/master/permissions" },
    ],
  },
  {
    label: "Approval",
    icon: CheckSquare,
    subItems: [
      { label: "Student Approval", href: "/approval/student" },
      { label: "Fee Approval", href: "/approval/fee" },
      { label: "Discount Approval", href: "/approval/discount" },
      { label: "Scholarship Approval", href: "/approval/scholarship" },
      { label: "Payment Approval", href: "/approval/payment" },
    ],
  },
  {
    label: "Reception",
    icon: Building2,
    subItems: [
      { label: "Visitors Entry", href: "/reception/visitors" },
      { label: "Pickup Authorization", href: "/reception/pickup" },
      { label: "Admission Enquiry", href: "/reception/enquiry" },
    ],
  },
  {
    label: "Bus & Route",
    icon: Bus,
    subItems: [
      { label: "All Buses", href: "/transport/buses" },
      { label: "Bus Location", href: "/transport/location" },
      { label: "Bus Routes", href: "/transport/routes" },
      { label: "Bus Attendance", href: "/transport/attendance" },
    ],
  },
  {
    label: "Reports",
    icon: FileBarChart,
    href: "/reports",
  },
  {
    label: "Certificate",
    icon: Award,
    href: "/certificates",
  },
  {
    label: "E-Request",
    icon: FileQuestion,
    href: "/requests",
  },
];
